### ISSUE TITLE
Add flag to trigger hashing full file when synchronizing

### ISSUE THREAD

**Issue by tdussa** [schollz/croc#368] opened 2021-04-17 08:42 UTC
On `croc` (version v8.6.12-c373b38), detection of whether a file is already present on the receiving side is not trustworthy.  As I understand it, a constant-time hash is used, meaning that not the entire file content is inspected, but only a fixed number of samples.  This, in turn, means that any differences in any other places are not detected.  This is entirely unexpected behavior.

Example:

Create a file of 10 MB of `\0`s, followed by an `A`, followed by 10 MB of `\0`s again, transfer it, then create the same file, but with a `B` instead of the `A`, transfer it again.  The second time, the file is *not* transferred because `croc` thinks the two files are identical (the debug output states that the hashes are identical).  Expected behavior would be to transmit the new file.

On the sender side:
```
~/croctest/send $ dd if=/dev/zero bs=10M count=1 > A; echo A >> A; dd if=/dev/zero bs=10M count=1 >> A
1+0 records in
1+0 records out
10485760 bytes (10 MB, 10 MiB) copied, 0,0329896 s, 318 MB/s
1+0 records in
1+0 records out
10485760 bytes (10 MB, 10 MiB) copied, 0,0147199 s, 712 MB/s
~/croctest/send $ croc send A
Sending 'A' (20.0 MB)
Code is: herbert-mars-jump
On the other computer run

croc herbert-mars-jump

Sending (->192.168.101.108:53286)
 100% |████████████████████| (20/20 MB, 45.569 MB/s)
~/croctest/send $ dd if=/dev/zero bs=10M count=1 > A; echo B >> A; dd if=/dev/zero bs=10M count=1 >> A
1+0 records in
1+0 records out
10485760 bytes (10 MB, 10 MiB) copied, 0,0273334 s, 384 MB/s
1+0 records in
1+0 records out
10485760 bytes (10 MB, 10 MiB) copied, 0,011334 s, 925 MB/s
~/croctest/send $ croc send A
Sending 'A' (20.0 MB)
Code is: formula-nothing-virus
On the other computer run

croc formula-nothing-virus
~/croctest/receive $ sum A
00043 20481
~/croctest/send $
```

And on the receiver side:
```
~/croctest/receive $ croc herbert-mars-jump 
Accept 'A' (20.0 MB)? (y/n) y

Receiving (<-[::1]:51542)
 100% |████████████████████| (20/20 MB, 45.438 MB/s)
~/croctest/receive $ croc formula-nothing-virus
Accept 'A' (20.0 MB)? (y/n) y

Receiving (<-[::1]:51596)
~/croctest/receive $
32810 20481
~/croctest/receive $
```

**Comment by schollz** [comment] 2021-04-17 13:16
Using a constant time hash is a tradeoff in my opinion that sacrifices accuracy for speed. Speed is important because I regularly use croc to transfer hundreds of gigabytes and hashing all that with SHA/similar is very slow. I've never experienced this flaky behavior with real data but do agree that it will miss edge cases like shown above.

Do you have a proposal to address the flaky behavior while making sure the speed is also not affected? I'd love to make this better but I've tried a couple of checksums and hashes and settled on one I thought best

**Comment by tdussa** [comment] 2021-04-17 15:15
In order to implement incremental transfer (i. e., resuming an interrupted transfer), `croc` somehow needs to figure out where to restart.  This essentially comes down to the same problem IIRC.  `croc` must somehow detect if, say, only the last megabyte is missing from a previous transfer.  How is this implemented then?

**Comment by schollz** [comment] 2021-04-17 15:41
> How is this implemented then?

croc writes to files in blocks. Any block anywhere can be written, they are not guaranteed to be in order. The unwritten blocks are all 0's. So when a file differs by hash, croc then checks whether there are blocks of 0's. If so, then only these blocks are sent as it is assumed the file is needing to be resumed.

**Comment by tdussa** [comment] 2021-04-17 16:14
Erm. O_o I'm even more confused now.  So... How does `croc` detect whether there are blocks of `0`s if it doesn't actually *read* all blocks?  And if it does, well, then running a hash of the data is comparatively cheap and should really not make a difference at all?

Furthermore, just assuming that there are no blocks of `0`s in the data is not good.  That should definitely *not* be assumed.  In fact, nothing at all should be assumed about the nature of the data to be transmitted IMHO...  IMHO the correct way to do this is to run hashes on all blocks and compare whether the hashes are identical or not.

**Comment by schollz** [comment] 2021-04-17 16:38
> How does croc detect whether there are blocks of 0s if it doesn't actually read all blocks?

If file hashes differ, then it does read all the blocks, of a specific size, to see if they are empty. Here's the relevant code: https://github.com/schollz/croc/blob/master/src/utils/utils.go#L169-L218

>  And if it does, well, then running a hash of the data is comparatively cheap and should really not make a difference at all?

The constant-time hash is ~1000x faster than MD5. So its expensive to use something like md5 to check every file initially. So the constant-time hash (imohash) is used to check all the files initially, which is fast. Then each file is individually checked for missing blocks, which is comparatively slow, but only adds a small fraction of time *if the file is being transferred*. I don't like the idea of taking lots of time to evaluate files that aren't going to be transferred, but if there is a better way I'm open to it!

> Furthermore, just assuming that there are no blocks of 0s in the data is not good. That should definitely not be assumed. In fact, nothing at all should be assumed about the nature of the data to be transmitted IMHO... IMHO the correct way to do this is to run hashes on all blocks and compare whether the hashes are identical or not.

Can you elaborate here - why is it not good?

**Comment by tdussa** [comment] 2021-04-17 17:28
I may have misphrased there.  I meant to say that if you read all blocks anyway, then reading and hashing should be about as fast as just reading, at least if you're I/O-bound.  (This, admittedly, might not always be the case.)

>> Furthermore, just assuming that there are no blocks of 0s in the data is not good.
> Can you elaborate here - why is it not good?

Sure, that's easy: Because that is an implicit assumption that files will never contain runs of zeros.  This would be okay-ish if it was explicitly mentioned in the documentation, but a tacit assumption is really, really bad, particularly if it is invalid.  There are plenty of legitimate files that contain lots of `0`s. Any binary format really can contain significant runs of zeroes, and in my particular use case, that's even quite likely.  So it most definitely is *not* a sign of data not having been transmitted correctly.  That is just a rather bold assumption that `croc` makes.  (Of course, admittedly, `croc` will err on the side of caution here and not break things, but if in doubt, it will result in significantly more data being transmitted than necessary.  In fact, in my use cases, it will likely result in never-ending retransmits because the files I am trying to transmit are so large and the network connection is so flaky that aborted transfers are not unlikely.  Then if every retransmit effectively -- when I am lucky and `croc` realizes that the file on the target system is actually _not_ the same as the source file, which is also unlikely, unfortunately -- restarts the entire transfer process.)

In the end, I am afraid, if `croc` is meant to transmit files with arbitrary data in a consistent and reliable way, then there is no way around either retransmitting the entire file every time or looking at the entire file if it looks like (part of) it has already been transmitted.  Otherwise every file transfer that is not complete is effectively a gamble on whether `croc` happens to detect changed/incomplete/missing data, if I understand correctly.

**Comment by schollz** [comment] 2021-04-17 18:05
> Sure, that's easy: Because that is an implicit assumption that files will never contain runs of zeros. This would be okay-ish if it was explicitly mentioned in the documentation, but a tacit assumption is really, really bad, particularly if it is invalid.

It can certainly go in the documentation. Happy to do that. However, the assumption croc makes about zero's being empty blocks doesn't seem to have ever affected my own transfers or others (based on the lack of issues being raised). And as you say, in worst case (if you are sending a bunch of files with just 0's) it requires extra bandwidth to re-transmit those empty blocks (though actually, probably not much bandwidth since plain 0's can be compressed and all transfers are compressed). So, from my point of view, it is not a bad assumption in that it has no serious consequences in practical situations that have ever been raised. Unless...

> the files I am trying to transmit are so large and the network connection is so flaky that aborted transfers are not unlikely. Then if every retransmit effectively -- when I am lucky and croc realizes that the file on the target system is actually not the same as the source file, which is also unlikely, unfortunately -- restarts the entire transfer process.

This sounds like a serious consequence in a practical situation. Can you share a demonstration of this behavior?

> Otherwise every file transfer that is not complete is effectively a gamble on whether croc happens to detect changed/incomplete/missing data, if I understand correctly.

I don't think the understanding is correct. Every file transfer that is not complete will have a block of zeros. *As long as the file itself is not a simply a bunch of zeros*, then croc will detect a changed file, then detect the missing blocks, and then resume file transfer. I have not seen any case otherwise, but would be open to results that show that this is not the case.

**Comment by Tragen** [comment] 2021-04-19 15:38
It's not perfect but wouldn't it help to hash different areas of the file so there is less chance to have the same hash?
e.h. Hash 10 MB of Data every Gigabyte and the end of the file.

**Comment by schollz** [comment] 2021-04-19 16:31
I should be more explicit here - croc uses [imohash](https://github.com/kalafut/imohash) to hash files:

https://github.com/schollz/croc/blob/333ece706e1f90436ca411275b857b156e13ae0c/src/utils/utils.go#L62

From the README of imohash:

> imohash is a fast, constant-time hashing library for Go. It uses file size and sampling to calculate hashes quickly, regardless of file size.

And it works in a way you describe @Tragen: 

> imohash works by hashing small chunks of data from the beginning, middle and end of a file.

Actually imohash is more sophisticated and clever than that, check out their README. But the main point is, imohash, is designed for file synchronization which is what is used for in croc. If there are better alternatives, I'd be eager to know.

**Comment by kalafut** [comment] 2021-04-20 03:23
@schollz imohash author here. The characterization here is correct: the only way to be 100% sure of catching differences is to hash the whole file. But the library is based on the assumption that in the vast majority of real world cases there is a quite small chance of false equality, and in return you get a big speedup.

I did want to mention that imohash has a [configurable mode](https://pkg.go.dev/github.com/kalafut/imohash?utm_source=godoc#NewCustom), including an setting to hash the whole file. So if you ever wanted to have an optional stronger mode in croc, you could keep a fairly uniform interface (i.e. just swap the hasher config). I never planned to use that mode myself and it is very simply implemented, reading in the whole file at once instead of chunking. That can be improved if needed. FWIW the underlying hash (murmurhash3) is quite a bit faster than md5.

**Comment by schollz** [comment] 2021-04-20 03:43
Hi @kalafut! Thanks so much for imohash! croc has probably been used to imohash millions and millions of files by now (the public relay regularly goes through ~8 terabytes of bandwidth, and that's just on the public relay!) I'm so glad that you created it. That's great to know about the configurable mode - I can turn that on and see what kind of affect is has. From my vantage point though, I haven't seen a failure from imohash in my transfers (and I transfer a lot of files at work....) nor have I seen any bug reports that I could interpret as an imohash failure. A all-around success for imohash - it really does seem to treat real world cases really well.

**Comment by tdussa** [comment] 2021-04-20 08:11
Sorry for the late reply.  I'm kinda busy these days, unfortunately.

> > Sure, that's easy: Because that is an implicit assumption that files will never contain runs of zeros. This would be okay-ish if it was explicitly mentioned in the documentation, but a tacit assumption is really, really bad, particularly if it is invalid.
> It can certainly go in the documentation. Happy to do that.

That would certainly be very much better than the current state.

> However, the assumption croc makes about zero's being empty blocks doesn't seem to have ever affected my own transfers or others (based on the lack of issues being raised).

Welp.  So this is the situation from my point of view.

The underlying problem is that imohash (in its constant-time mode) cannot reliably detect whether two files are identical, as @kalafut has confirmed.  I cannot overstate how problematic that can be.  The best case obviously is that for two different files, the imohash sums are, indeed, different.  It may very well be that for particular use cases, this is very likely or even guaranteed, but that entirely depends on the circumstances of the use case.  If all you're transferring is just a set of static files, say, JPEG images from A to B, then this problem will likely never hit you.  However, there *are* circumstances where the likelihood of this problem arising is actually very close to 1, i. e., it is virtually guaranteed that you run into this problem.  My particular use case happens to be one of those examples, as I'll explain later.  The point is that `croc` cannot unconditionally claim to support things like picking up aborted transmissions if its ability to do so depends on the circumstances of the use case to be just right for the imohash detection method to work.  Such a claim is misleading at best and leads to potentially very serious problems at worst (if you happen to trust `croc` to have transferred your data correctly when, in fact, it silently did not do so).  In order to compare whether two files are identical, in the end, if there are no other indications to assume that they are not identical, you *have* to read both files completely and compare their contents (whether or not you hash the contents is irrelevant: you *have* to read every last bit of data in *both* files.  That's a mathematical fact.  Obviously, this takes time, and of course, you can take shortcuts to try to guesstimate (because that's what it is) whether two files are identical.  However, this comes at a cost.

Now, I see two situations in which this problem can hit the user:
1. When transmitting a different version of a file that is present on the target system already and
2. when picking up an aborted transmission.

These cases are quite different, so I'll discuss them seperately.

Case 1 can easily happen whenever there are small changes in large files that do not result in changes of the file size.  Examples of this are some image or sound file formats or, indeed, disk images (the latter happens to be my use case here).  This can very easily be addressed by merely defining that `croc` will not try to determine whether an existing file is identical, but rather ignores it and retransmits the file as if the old file never existed.

Case 2 is even nastier.  If a file is partially transmitted, then by definition, some blocks of that file have been transferred to the target system successfully.  The exact sequence of blocks transmitted is undefined, so it is possible that those blocks that *are* checked by imohash have already been transmitted successfully (or, indeed, happen to be identical for other reasons).  The first line of defense, so to speak, namely the file _size_ is _guaranteed_ to be identical because `croc` allocates the entire file at the beginning of the transfer and fills it with `\0`s.  Incidentally, this also means that whenever one of the blocks that imohash happens to check actually contains just `\0`s (as is often the case in file-system images), then the probability of incomplete file transfers to be detected by comparing imohash constant-time hashes further decreases.  In fact, once you have successfully transmitted the first half of the file, retransmission will never(!) work if the last block of the file happens to be filled with `\0`s, because, well, imohash just checks the size (which is identical by definition), and the first, middle, and last blocks, all of which are identical even though half the file has not been transmitted.

So, you can see, my particular use case (transmitting large disk images that contain lots of runs of `\0`s) pretty much guarantees that things will break in totally unexpected ways.  In fact, this is not just a nuisance in my case, it actually *prevents* me from transferring data with `croc` (not because I don't want to run the risk or so, but because `croc` will just refuse to transmit the rest of the data once half of a file is there, but the transfer broke down).

From my point of view, frankly, a tool that claims to transfer files implicitly claims to transfer files *reliably*, and this just is not the case for `croc` right now.  (Frankly, I was very surprised when I discovered this, to put it very mildly.  This is a showstopper for many, many applications.)  At the very least, these characteristics of `croc` *must* be made explicit to the user, and IMHO putting it in the documentation is not even sufficient, TBH.  This should really be displayed as a warning directly by the program whenever the situation arises.  Anything less than that will eventually result in people losing data and not even noticing it until it is too late.  (You might even have lost data without realizing it.)

I totally appreciate that there are use cases in which the constant-time hash shortcut is absolutely fine because, well, you can pretty much rule out that anything bad happens (or you are at least willing to take the risk).  However, I do think that that is a very dangerous behavior of `croc` and as such should most definitely not be the default mode.  I think the correct way to do it is to have a command-line switch that turns on constant-time hashing instead of a more time-consuming, but safe comparison mode.

> And as you say, in worst case (if you are sending a bunch of files with just 0's) it requires extra bandwidth to re-transmit those empty blocks (though actually, probably not much bandwidth since plain 0's can be compressed and all transfers are compressed). So, from my point of view, it is not a bad assumption in that it has no serious consequences in practical situations that have ever been raised. Unless...

Yep. Exactly. Unless you have been lucky enough that your particular set of circumstances has prevented that from happening. ;-)

> This sounds like a serious consequence in a practical situation. Can you share a demonstration of this behavior?

Not sure what you want here, actually. :)  You don't really want me to submit a 500-GB disk image here, I guess. ;-)

> > Otherwise every file transfer that is not complete is effectively a gamble on whether croc happens to detect changed/incomplete/missing data, if I understand correctly.
> I don't think the understanding is correct. Every file transfer that is not complete will have a block of zeros. _As long as the file itself is not a simply a bunch of zeros_, then croc will detect a changed file, then detect the missing blocks, and then resume file transfer. I have not seen any case otherwise, but would be open to results that show that this is not the case.

I don't think that is incorrect.  I have looked at the imohash source code, and unless I am reading the code wrong, imohash essentially hashes the first, the middle, and the last blocks (plus the file size).  This means, as I have laid out above, that all it takes for this to fail is for three(!) blocks to be identical in both the source and the target files.  By no means does a file need to contain only `\0`s for this to be a problem (although, just for the record, even such a file should be safely and reliably transmitted by `croc`).

**Comment by schollz** [comment] 2021-04-20 13:26
Thanks @tdussa. I'd still like an example of these behaviors. You say it won't work for disk images, sound files, or images. Can you please try recording your terminals while transferring these unsuccessfully? You can use https://asciinema.org/ and use `croc --debug` to send and receive. If you can't use asciinema, please just use `croc --debug` and share the output. I'd like to see a real example of this occurring. I do understand your points above, but I do also need to see evidence of a problem in this case.

For the many-GB disk image problem, it's a pretty easy fix - I can just switch imohash to hashing an entire file if it exceeds a certain size (say > 1 GB). That would fix your "case 1" and "case 2" for disk images. I've never heard of or seen a case 1 with sound files or images (I transfer a *lot* of both for work), but if you can demonstrate this, please do.

Once you found an example of poor transferring of your files, try this branch (https://github.com/schollz/croc/tree/imohash) which uses the full hash (make sure both sender and receiver are built from that branch) to see if it fixes.

**Comment by schollz** [comment] 2021-04-20 16:35
> Maybe an alternative would be some sort of config around types or locations of files that will always have a full hash?

Yeah I like this idea and thought about that. I need data on failed cases to figure out the heuristics for this and to see if its viable.


> Does croc independently check file size first, before the hashing? 

The sender does gather file size info and send it to the receiver. The receiver doesn't do anything with this info at the moment, though. However that is a good little upgrade to do that! I've made a commit along those lines: https://github.com/schollz/croc/compare/v91 That should improve performance in the case you are updating a lot of files from one computer to the other and the recipient has the same files but they are all different sizes.

> lest you end up with OOM errors trying to read a massive disk image into memory

Ooooh! Does hashing the whole file load it all into memory? I was under the impression it was streamed.

**Comment by tdussa** [comment] 2021-04-20 16:52
> Thanks @tdussa. I'd still like an example of these behaviors. You say it won't work for disk images, sound files, or images. Can you please try recording your terminals while transferring these unsuccessfully? You can use https://asciinema.org/ and use `croc --debug` to send and receive. If you can't use asciinema, please just use `croc --debug` and share the output. I'd like to see a real example of this occurring. I do understand your points above, but I do also need to see evidence of a problem in this case.

Wait, just so I understand this correctly.  I have explicitly written down the exact command lines that you can use to reproduce this problem, but these files are not good enough to figure out how `croc` behaves?  Or don't you believe that any binary data of fixed size can run into this problem?  The image and sound files were just examples that I could think of off the top of my hat.  How would it help if I took an image and edited it so it triggers the problem?  I don't see the point, frankly, but hey.  I took a screenshot of this and painted in a copy of it.  I'll attach a thumbnail of the images here, and because of the v9 change I cannot actually send it around right now (I've already auto-updated my own relay, unfortunately), but I don't think it matters.  I just told `croc` to send both files with debug output turned on, that displays the hashes generated for both files.  As you can see, the hashes are identical, just as predicted.  I'll attach a mini version of the files side by side so you have an idea what I did (I really just put a blot of color somewhere at random).  Here's the CLI output:
```
~/croctest $ ls -l
total 4864
-rw-rw-r-- 1 tdussa tdussa 2486645 Apr 20 18:28 test-A.tif
-rw-rw-r-- 1 tdussa tdussa 2486645 Apr 20 18:36 test-B.tif
~/croctest $ feh *
~/croctest $ sum *
54771  2429 test-A.tif
24208  2429 test-B.tif
~/croctest $ croc --debug send * 2>&1 | fgrep -i hash
[debug]	18:38:01 croc.go:250: file 1 info: {Name:test-A.tif FolderRemote:. FolderSource:/home/tdussa/croctest/ Hash:[245 226 151 1 34 188 168 164 12 141 218 223 50 50 110 38] Size:2486645 ModTime:2021-04-20 18:28:53.514964439 +0200 CEST IsCompressed:false IsEncrypted:false Symlink:}

[debug]	18:38:01 croc.go:250: file 0 info: {Name:test-B.tif FolderRemote:. FolderSource:/home/tdussa/croctest/ Hash:[245 226 151 1 34 188 168 164 12 141 218 223 50 50 110 38] Size:2486645 ModTime:2021-04-20 18:36:10.879298661 +0200 CEST IsCompressed:false IsEncrypted:false Symlink:}
```

> For the many-GB disk image problem, it's a pretty easy fix - I can just switch imohash to hashing an entire file if it exceeds a certain size (say > 1 GB). That would fix your "case 1" and "case 2" for disk images. I've never heard of or seen a case 1 with sound files or images (I transfer a _lot_ of both for work), but if you can demonstrate this, please do.

Here you go.  You can run into this problem with any two files, provided that they are large enough so that imohash doesn't completely hash them.

> Once you found an example of poor transferring of your files, try this branch (https://github.com/schollz/croc/tree/imohash) which uses the full hash (make sure both sender and receiver are built from that branch) to see if it fixes.

THX, will do.

![test-A-B-side_by_side](https://user-images.githubusercontent.com/6197517/115434872-7a962e00-a209-11eb-9c79-9b3a8cdfdd1f.png)

**Comment by schollz** [comment] 2021-04-20 17:00
@tdussa Can you share these images? You can just paste them into this issue. I tried doing the same process but cannot reproduce (if I add a tiny dot to an image as you did it will increase the file size).

**Comment by tdussa** [comment] 2021-04-20 17:01
> > Maybe an alternative would be some sort of config around types or locations of files that will always have a full hash?
> Yeah I like this idea and thought about that. I need data on failed cases to figure out the heuristics for this and to see if its viable.

Please, please, please don't try to cover this problem under yet another layer of guesswork.  IMHO, it's totally fine if people can tell `croc` to use the imohash constant-time hash strategy if they want to, but the default behavior should really, really, really be the reliable way without any guesstimating and relying on good luck whether it'll work fine.  It's really that simple.  Just add a switch that flicks on the imohash optimization if the user (who is the only one in the position to decide whether that risk is a problem for her use case or not) wants it.  That's totally cool.  But do not bury the problem under a ton of heuristics that makes it even harder to understand for the user what's going on.

**Comment by tdussa** [comment] 2021-04-20 17:04
> @tdussa Can you share these images? You can just paste them into this issue. I tried doing the same process but cannot reproduce (if I add a tiny dot to an image as you did it will increase the file size).

Well, you have to use a file format that is _constant_ in size, obviously.  I used TIFF to illustrate this.  But again, WHY do you need the files?  What good does that do?  You do have a working example already?

[test_images.zip](https://github.com/schollz/croc/files/6345362/test_images.zip)

**Comment by schollz** [comment] 2021-04-20 17:08
Okay thanks @tdussa. Seems like a flag is an easy solution!

**Comment by kalafut** [comment] 2021-04-20 17:18
>Ooooh! Does hashing the whole file load it all into memory? I was under the impression it was streamed.

@schollz Currently it does, but only because that was the code path expected for very small files and that was a simple approach. The change to streaming is pretty easy to make and I will do so. I'll drop a note when there is a new version you can pull in.

**Comment by schollz** [comment] 2021-04-20 17:32
Side note to @tdussa: I really appreciate your passion and expertise, and you've provided some great insights. Currently I'm finding your tone to be pretty indignant and a little bit rude. I want to support and welcome all points of views and expertise and would appreciate it you can be more respectful as this kind of current discourse might be discouraging to other users/collaborators. Lets continue to engage, if you want, but lets do it in a way that is clear as well as kind.

**Comment by schollz** [comment] 2021-04-20 23:06
Okay v9.1.0 has an optional hash flag now (not yet available as a CLI argument) and it defaults to [xxhash](https://github.com/cespare/xxhash) which fixes the issue raised with that example of the two constant-size TIFF images.

**Closed by schollz** 2021-04-20 23:06 UTC
Labels: bug
