### ISSUE TITLE
extra progress file not deleted when transfer finished

### ISSUE THREAD

**Issue by codeskyblue** [schollz/croc#100] opened 2018-10-22 09:53 UTC
```
-rw-r--r-- 1 pi pi    18 Oct 22 09:48 run-cow.sh
-rw-r--r-- 1 pi pi     2 Oct 22 09:48 run-cow.sh.progress
```

**Comment by schollz** [comment] 2018-10-22 13:45
@codeskyblue Can you print the version of croc? Also can you do the sender and receiver in debug mode (add `--debug`) and paste the content here? This is not a behavior I've seen before.

**Comment by schollz** [comment] 2018-10-25 14:07
Closing now, let me know if you have more information

**Comment by codenoid** [comment] 2018-12-21 08:56
weird bug,

`croc version "v4.1.4-2018-11-06T03:06:41Z"`

*.progress file not deleted on first-try download

**Comment by schollz** [comment] 2018-12-21 18:46
@codenoid, is this reproducible?

**Comment by schollz** [comment] 2019-05-03 00:27
This shouldn't be an issue anymore since progress files are no longer used in v6.

**Closed by schollz** 2019-05-03 00:27 UTC
Labels: need more information
