### ISSUE TITLE
checksum verification

### ISSUE THREAD

**Issue by camjac251** [schollz/croc#221] opened 2020-05-19 16:48 UTC
If I'm not mistaken, files are currently updated if the size or date changes? I've noticed sometimes when it hangs on a file and you interrupt the process to restart it, those files that are corrupt but same date/length are not retrieved again.

Are there plans for checksum comparisons of files?

**Comment by schollz** [comment] 2020-09-03 20:18
> If I'm not mistaken, files are currently updated if the size or date changes? 

Files are updated if the hash changes. The size may be the same (because different bytes can be the same number of bytes), and the date is not computed as part of the hash.

> Are there plans for checksum comparisons of files?

After file transfer, both parties check the hash of their files, and this is, by definition, a "checksum comparison".

> I've noticed sometimes when it hangs on a file and you interrupt the process to restart it, those files that are corrupt but same date/length are not retrieved again.

This sounds like a bug. Is it reproducible? Are you sure the file being transferred is not being written to during the transfer?

**Closed** 2020-09-07 15:28 UTC

**Comment by camjac251** [comment] 2020-09-07 17:44
Oh my bad I forgot to reply. It was a while ago that I had these issues and haven't used croc as much recently. Next time I face the issue I'll let you know here.
