### ISSUE TITLE
Memory leak in relay

### ISSUE THREAD

**Issue by maximbaz** [schollz/croc#205] opened 2020-03-24 20:03 UTC
I'm running a relay and I noticed that it consumes huge amount of RAM:

![image](https://user-images.githubusercontent.com/1177900/77471140-13455900-6e12-11ea-942a-ae70e3b471af.png)

In fact I haven't even used croc in a few days.

It runs in `docker-compose` as so:

```yaml
version: "3.7"

services:
  croc:
    image: schollz/croc
    restart: always
    ports:
      - "9009:9009"
      - "9010:9010"
      - "9011:9011"
      - "9012:9012"
      - "9013:9013"
    command: "--pass XXXX relay"
```

in `docker-compose logs` I see a ton of either port scans or failed attempts to use my relay (I assume failed, because they don't know the password... hopefully):

```
croc_1  | [warn]	2020/03/22 08:35:11 relay-45.136.108.67:1464: read tcp 172.21.0.2:9010->45.136.108.67:1464: read: connection reset by peer
croc_1  | [warn]	2020/03/22 19:53:34 relay-92.63.194.15:670: read tcp 172.21.0.2:9010->92.63.194.15:670: read: connection reset by peer
croc_1  | [warn]	2020/03/23 00:30:46 relay-198.108.67.48:48788: read tcp 172.21.0.2:9011->198.108.67.48:48788: read: connection reset by peer
croc_1  | [warn]	2020/03/23 00:30:47 relay-198.108.67.48:57744: read tcp 172.21.0.2:9011->198.108.67.48:57744: read: connection reset by peer
croc_1  | [warn]	2020/03/23 00:30:48 relay-198.108.67.48:3586: read tcp 172.21.0.2:9011->198.108.67.48:3586: read: connection reset by peer
croc_1  | [warn]	2020/03/23 13:34:51 relay-85.93.20.170:65357: read tcp 172.21.0.2:9009->85.93.20.170:65357: read: connection reset by peer
croc_1  | [warn]	2020/03/23 14:32:41 relay-223.71.167.163:8870: EOF
croc_1  | [warn]	2020/03/23 16:36:22 relay-185.209.0.76:1104: read tcp 172.21.0.2:9010->185.209.0.76:1104: read: connection reset by peer
croc_1  | [warn]	2020/03/24 09:38:40 relay-182.92.107.76:43560: EOF
croc_1  | [warn]	2020/03/24 09:38:45 relay-182.92.107.76:43608: EOF
croc_1  | [warn]	2020/03/24 09:38:50 relay-182.92.107.76:43622: EOF
croc_1  | [warn]	2020/03/24 09:38:55 relay-182.92.107.76:43642: EOF
croc_1  | [warn]	2020/03/24 09:39:00 relay-182.92.107.76:43660: EOF
croc_1  | [warn]	2020/03/24 09:39:06 relay-182.92.107.76:43678: EOF
croc_1  | [warn]	2020/03/24 09:39:12 relay-182.92.107.76:43694: EOF
croc_1  | [warn]	2020/03/24 09:39:20 relay-182.92.107.76:43742: EOF
croc_1  | [warn]	2020/03/24 09:39:25 relay-182.92.107.76:43774: EOF
croc_1  | [warn]	2020/03/24 09:39:30 relay-182.92.107.76:43792: EOF
croc_1  | [warn]	2020/03/24 09:39:35 relay-182.92.107.76:43806: EOF
croc_1  | [warn]	2020/03/24 09:39:45 relay-182.92.107.76:43828: EOF
croc_1  | [warn]	2020/03/24 09:39:46 relay-182.92.107.76:43848: EOF
croc_1  | [warn]	2020/03/24 09:39:51 relay-182.92.107.76:43866: EOF
croc_1  | [warn]	2020/03/24 09:39:56 relay-182.92.107.76:43886: EOF
croc_1  | [warn]	2020/03/24 09:40:02 relay-182.92.107.76:43918: EOF
croc_1  | [warn]	2020/03/24 09:40:07 relay-182.92.107.76:43948: EOF
croc_1  | [warn]	2020/03/24 09:40:15 relay-182.92.107.76:43988: EOF
croc_1  | [warn]	2020/03/24 09:40:20 relay-182.92.107.76:44022: EOF
croc_1  | [warn]	2020/03/24 09:40:25 relay-182.92.107.76:44056: EOF
croc_1  | [warn]	2020/03/24 09:40:31 relay-182.92.107.76:44094: EOF
croc_1  | [warn]	2020/03/24 09:40:36 relay-182.92.107.76:44132: EOF
croc_1  | [warn]	2020/03/24 09:40:41 relay-182.92.107.76:44152: EOF
croc_1  | [warn]	2020/03/24 09:41:20 relay-182.92.107.76:44200: EOF
croc_1  | [warn]	2020/03/24 09:41:20 relay-182.92.107.76:44230: EOF
croc_1  | [warn]	2020/03/24 09:41:20 relay-182.92.107.76:44178: EOF
croc_1  | [warn]	2020/03/24 09:41:21 relay-182.92.107.76:44250: EOF
croc_1  | [warn]	2020/03/24 09:41:21 relay-182.92.107.76:44280: EOF
croc_1  | [warn]	2020/03/24 09:41:26 relay-182.92.107.76:44342: EOF
croc_1  | [warn]	2020/03/24 09:41:31 relay-182.92.107.76:44376: EOF
croc_1  | [warn]	2020/03/24 09:41:32 relay-182.92.107.76:1011: EOF
croc_1  | [warn]	2020/03/24 12:10:19 relay-45.136.108.68:314: read tcp 172.21.0.2:9012->45.136.108.68:314: read: connection reset by peer
croc_1  | [warn]	2020/03/24 18:59:12 relay-198.108.67.48:42524: read tcp 172.21.0.2:9009->198.108.67.48:42524: read: connection reset by peer
croc_1  | [warn]	2020/03/24 18:59:12 relay-198.108.67.48:49112: read tcp 172.21.0.2:9010->198.108.67.48:49112: read: connection reset by peer
croc_1  | [warn]	2020/03/24 18:59:12 relay-198.108.67.48:13786: read tcp 172.21.0.2:9011->198.108.67.48:13786: read: connection reset by peer
croc_1  | [warn]	2020/03/24 18:59:12 relay-198.108.67.48:42462: read tcp 172.21.0.2:9012->198.108.67.48:42462: read: connection reset by peer
croc_1  | [warn]	2020/03/24 18:59:12 relay-198.108.67.48:38194: read tcp 172.21.0.2:9013->198.108.67.48:38194: read: connection reset by peer
croc_1  | [warn]	2020/03/24 18:59:13 relay-198.108.67.48:48878: read tcp 172.21.0.2:9009->198.108.67.48:48878: read: connection reset by peer
croc_1  | [warn]	2020/03/24 18:59:13 relay-198.108.67.48:56930: read tcp 172.21.0.2:9010->198.108.67.48:56930: read: connection reset by peer
croc_1  | [warn]	2020/03/24 18:59:13 relay-198.108.67.48:57708: read tcp 172.21.0.2:9012->198.108.67.48:57708: read: connection reset by peer
croc_1  | [warn]	2020/03/24 18:59:13 relay-198.108.67.48:28824: read tcp 172.21.0.2:9011->198.108.67.48:28824: read: connection reset by peer
croc_1  | [warn]	2020/03/24 18:59:13 relay-198.108.67.48:54196: read tcp 172.21.0.2:9013->198.108.67.48:54196: read: connection reset by peer
croc_1  | [warn]	2020/03/24 18:59:15 relay-198.108.67.48:34946: read tcp 172.21.0.2:9009->198.108.67.48:34946: read: connection reset by peer
croc_1  | [warn]	2020/03/24 18:59:15 relay-198.108.67.48:49106: read tcp 172.21.0.2:9010->198.108.67.48:49106: read: connection reset by peer
croc_1  | [warn]	2020/03/24 18:59:15 relay-198.108.67.48:43464: read tcp 172.21.0.2:9011->198.108.67.48:43464: read: connection reset by peer
croc_1  | [warn]	2020/03/24 18:59:15 relay-198.108.67.48:7878: read tcp 172.21.0.2:9012->198.108.67.48:7878: read: connection reset by peer
croc_1  | [warn]	2020/03/24 18:59:15 relay-198.108.67.48:13390: read tcp 172.21.0.2:9013->198.108.67.48:13390: read: connection reset by peer
```

I am speculating that maybe such connections confuse relay and make it leak memory.

Restarting the relay brings memory usage down to 12MB.

Let me know if I can help you with anything.

**Comment by schollz** [comment] 2020-03-24 22:29
I suppose it could be due to connections that fail. I will look into it.

I'll see if I can reproduce this too. Interestingly I'm also running the main relay in docker and I'm seeing very little memory usage despite transferring over 500GB:

```
CONTAINER ID        NAME                  CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
ceea780b4e50        croc                  0.00%               7.105MiB / 985.2MiB   0.72%               529GB / 524GB       0B / 0B             9
```

**Comment by maximbaz** [comment] 2020-03-25 09:20
12 hours later after restart, I haven't used my croc relay, and it grew to 1G of RAM:

![image](https://user-images.githubusercontent.com/1177900/77520825-11b37980-6e82-11ea-9521-37ddf09c3ca1.png)

```
$ docker-compose logs -f 
Attaching to croc_croc_1
croc_1  | [info]	2020/03/24 19:56:06 starting TCP server on 9009
croc_1  | [info]	2020/03/24 19:56:06 starting TCP server on 9010
croc_1  | [info]	2020/03/24 19:56:06 starting TCP server on 9012
croc_1  | [info]	2020/03/24 19:56:06 starting TCP server on 9011
croc_1  | [info]	2020/03/24 19:56:06 starting TCP server on 9013
croc_1  | [warn]	2020/03/25 00:10:15 relay-195.62.46.5:53993: EOF
croc_1  | [warn]	2020/03/25 02:49:34 relay-94.102.49.193:52982: EOF
```

I made sure to pull latest image before the restart yesterday, just in case.

**Comment by schollz** [comment] 2020-03-27 14:59
What happens if you don't use docker? You can just grab the latest release and run it as a relay. I'm using Docker too, but I don't use docker-compose and would like to eliminate that as a potential problem.

**Comment by maximbaz** [comment] 2020-03-27 16:15
I've ran the relay directly from the binary, and to simulate the idea of port scanning, I ran the following command:

```
$ sudo nmap -v -sV -T4 -p9009-9014 <croc-relay-ip-addr>
```

This has completely destroyed the relay, it used up all available RAM on my system in a matter of seconds and got killed.

Do you think this experiment helps going in the right direction?

I don't want to run this against your public relay, I leave this up to you 😄

**Comment by schollz** [comment] 2020-03-27 16:18
Lol that is perfect. I'll use your `nmap` command to diagnose :+1:

**Comment by schollz** [comment] 2020-03-27 16:35
Okay, based on the port scanning problem this is a fix: https://github.com/schollz/croc/commit/b60a841044f6ab81a7f95c8c6e9fdc75878e94f2#diff-c27706ced4c7f3ae58c1bef86fe74e21R99-R103

The comm I'm using asks the sender to declare how many bytes they are sending. Somehow the `nmap`  was declaring it wanted to send millions of bytes, causing the comm to allocate that every time. It was a memory explosion on my computer too lol. I added a protection against this with that commit.

**Comment by maximbaz** [comment] 2020-03-27 16:47
I confirm that my example with nmap is indeed resolved indeed, thanks :) 

To better understand your fix, you are asking the sender how many bytes they are planning to send and allocating that much memory, is there a chance that the memory will not be deallocated? Maybe if the sender silently disappears, or stops sending mid-way? I'm still thinking how to explain the high memory usage I saw in real life, where croc didn't explode, but remained at ~10GB usage for a long time...

**Comment by maximbaz** [comment] 2020-03-27 16:50
Do you also limit the number of active senders? With the current limit of 1000000 bytes, is it possible that someone will issue a 10000 parallel sending requests that will again allocate 10GB? If so, can we protect against this somehow?

**Comment by schollz** [comment] 2020-03-27 16:51
@maximbaz Yeah, I can't really explain that. The memory is allocated until disconnection or until all of the bytes are read from the connection. Maybe its possible that whatever connected didn't disconnect?

**Comment by schollz** [comment] 2020-03-27 16:52
> Do you also limit the number of active senders? With the current limit of 1000000 bytes, is it possible that someone will issue a 10000 parallel sending requests that will again allocate 10GB? If so, can we protect against this somehow?

Yeah, I think a relay should be rate-limited to prevent this.

**Comment by maximbaz** [comment] 2020-03-27 16:52
> Maybe its possible that whatever connected didn't disconnect?

I can imagine this happening... Maybe we can add something simpler, a ticker that will kill the connection if the sender didnt send any bytes for the last N seconds?

**Comment by schollz** [comment] 2020-03-27 16:57
> I can imagine this happening... Maybe we can add something simple, a ticker that will kill the connection if the sender didnt send any bytes for the last N seconds?

This is a good idea. The underlying tcp connection has a read deadline. Right now I have a deadline of 3 hours because some people like to send a file and then the receive may wait hours before receiving. However, since there are two steps to the comm (read the header, then read the specified bytes) I can add two deadlines - a long one to read the header and then a short one to read the specified bytes.

**Closed** 2020-04-09 14:41 UTC

**Comment by maximbaz** [comment] 2020-04-09 15:33
Thanks @schollz! FYI I've been running my relay on 8.0.5 for a short while, my log is full of "too many bytes" and "connection reset by peer", but memory usage is 21MB! I consider this a success 😄 

By the way, maybe don't log an "error" in comm.go ( [here](https://github.com/schollz/croc/blob/9bf470ef29605ed4ae6313710cfd8b4ec1c61c02/src/comm/comm.go#L104) ), as it's being logged as warning later anyway?

```
croc_1  | [error]	2020/04/07 21:39:37 comm.go:101: too many bytes: 542393671
croc_1  | [warn]	2020/04/07 21:39:37 relay-198.20.87.98:57683: too many bytes: 542393671
croc_1  | [error]	2020/04/07 23:29:40 comm.go:101: too many bytes: 788529155
croc_1  | [warn]	2020/04/07 23:29:40 relay-85.93.20.106:1628: too many bytes: 788529155
croc_1  | [error]	2020/04/07 23:35:04 comm.go:101: too many bytes: 788529155
croc_1  | [warn]	2020/04/07 23:35:04 relay-85.93.20.106:1602: too many bytes: 788529155
croc_1  | [error]	2020/04/08 00:14:58 comm.go:101: too many bytes: 788529155
croc_1  | [warn]	2020/04/08 00:14:58 relay-85.93.20.106:1400: too many bytes: 788529155
croc_1  | [error]	2020/04/08 00:17:22 comm.go:101: too many bytes: 788529155
croc_1  | [warn]	2020/04/08 00:17:22 relay-85.93.20.106:1559: too many bytes: 788529155
croc_1  | [error]	2020/04/08 00:17:26 comm.go:101: too many bytes: 788529155
croc_1  | [warn]	2020/04/08 00:17:26 relay-85.93.20.106:1750: too many bytes: 788529155
```

**Comment by schollz** [comment] 2020-04-09 16:13
Great! Yeah those can both be debugs. I'll fix those
