### ISSUE TITLE
Croc should tell the user if they are using an incompatible version from the relay.

### ISSUE THREAD

**Issue by Alexnortung** [schollz/croc#397] opened 2021-05-21 16:24 UTC
**Is your feature request related to a problem? Please describe.**
I have had croc installed on my laptop and my dektop, both version 8. I was trying to use the public relay to transfer a file, but I just got a message ending in `connection reset by peer`. I understand that this is because version 8 is not compatible with version 9.

**Describe the solution you'd like**
My suggestion is that the croc client should output a meaningful message, like "the relay does not support this verison of croc".

**Comment by mawoka-myblock** [comment] 2021-07-08 09:01
It is kind of a duplicate of #386

**Closed** 2021-09-05 08:24 UTC
