### ISSUE TITLE
windows 10 Transport folder An error

### ISSUE THREAD

**Issue by tnjc999** [schollz/croc#444] opened 2021-12-10 09:03 UTC
windows 10 Transport folder An error
An error
C:\FTP>croc.exe send C:\1mi\
2021/12/10 16:58:58 remote directory must be relative to current
C:\FTP>croc.exe send C:\1mi
2021/12/10 16:58:59 remote directory must be relative to current

**Comment by hamiecod** [comment] 2021-12-25 01:26
This error is not Windows specific. It is a duplicate of #431.

**Closed** 2024-03-08 12:29 UTC
Labels: bug, no-issue-activity
