### ISSUE TITLE
room not ready, windows 10 cant make it work

### ISSUE THREAD

**Issue by regularperson2586** [schollz/croc#382] opened 2021-04-25 05:37 UTC
## Describe the bug
<-- A clear and concise description of what the bug is. -->
when i try to send something to a friend mac -> windows it  says "room not ready" on his end (windows)
then I tried on my own windows computer, and its the same.

## To Reproduce
<-- 1. Go to '...'
4. See error -->

1.On mac  i send the file
2. on windows enter the code
3.it says room not ready
4. 
I tried to do another thing on windows, just to check, tried croc upgrade, and the same, it says " room not ready" 

## Expected behaviour
<-- A clear and concise description of what you expected to happen. -->

## Version
<-- Check "croc -v" and report it -->
 I have the version 9.1.0

## Additional context
<-- Add any other context about the problem here. -->

**Comment by shoman4eg** [comment] 2021-04-27 14:27
Check both croc versions on mac and win.

**Comment by Whoareyouagain** [comment] 2021-04-28 00:45
Hello, I have the same issue as this OP.

Operating Systems: Window 10 20H2 and macOS Big Sur 11.3 (Macbook Air M1)
Croc Version: `9.1.0-35106d4`(both OS), past version have same issue
Package Managers: Scoop/Chocolatey (Windows), Homebrew (macOS).
Window consoles: Powershell, cmd, cmder, Window Terminals & bash via cmder (Tried in non-elevated & elevated mode) 
macOS consoles: Terminal.app & iTerm2  (tried in user mode & sudo)
How long is this issue: Issue start appearing February 2021 (started using croc since mid-January 2021)
Reproduce-able: Yes, but not consistently
Firewall Rule: Yes, allowed in both systems

I created a file in my window desktop (docx with image inside) and open up PowerShell in elevated mode. I ran it in elevated mode because Croc get more flakey when running in non-admin mode. And typed down the command `croc send doc1.docx` then it outputted the passcode that it asked me to put in other device. I went on macOS and open up Terminal.app and run `croc <insert_passcode>` and then the error happened with "Room not ready" message. 

It didn't matter which system, both of them will receive room not ready error as a receiving end. I tried to run it with various options (`--no-compress`, `--local`, & `--remember`). My Window 10 device is connected through the ethernet and the Macbook Air is connected through WiFi. My Windows Croc is installed via Scoop currently.

I ran it with `--debug` option just before this comment and produced a log from both system that occurred at the same time. This time I was using bash via cmder in elevated mode in Windows and Terminal.app in macOS. 

I hope this information helps. If you need more from me, let me know what I need to do. 

[Window 10 Home 20H2.txt](https://github.com/schollz/croc/files/6388361/Window.10.Home.20H2.txt)
[macOS Big Sur 11.3 M1.txt](https://github.com/schollz/croc/files/6388362/macOS.Big.Sur.11.3.M1.txt)

**Comment by regularperson2586** [comment] 2021-04-28 03:58
> Check both croc versions on mac and win.

This fixed it for me. Didn't know two different versions weren't compatible. Thanks.

**Comment by camjac251** [comment] 2021-04-28 23:28
I have been facing this issue very often over the last 2 months. `Room not ready`
Both computers are on the same croc version as well. I've been wondering if it's due to the recipient using IPv6 before IPv4, when the sender only has IPv4.

**Comment by schollz** [comment] 2021-04-29 15:05
@camjac251 please post a new issue and please follow the template. e.g. which versions of croc, which operating system, etc.

> This fixed it for me. 
closing issue then

**Closed by schollz** 2021-04-29 15:05 UTC
Labels: bug

**Comment by DiracSpace** [comment] 2021-12-28 15:53
> open up PowerShell in elevated mode.

This helped, thanks!

**Comment by SomwareHR** [comment] 2024-09-08 08:24
> Check both croc versions on mac and win.

Then all listed options to install on Windows are actually useless because it installs something like v9.6.4-1fce28e.
